apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx002
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:latest
      nodeSelector:
        loong: abc
